services:
  # -------------------------------------
  # Prefect Orion Server
  # -------------------------------------
  prefect:
    image: prefecthq/prefect:3.4-python3.10
    container_name: prefect_server
    command: prefect server start --host 0.0.0.0
    ports:
      - "4200:4200"
    volumes:
      - prefect_data:/root/.prefect
    environment:
      PREFECT_API_URL: http://localhost:4200/api

volumes:
  prefect_data:
