version: 2

models:
  - name: int_campaign_performance
    description: >
      Aggregates daily impressions and clicks per campaign, with campaign metadata,
      and flags where impressions are not greater than clicks.
    columns:
      - name: event_date
        description: "Date of the campaign activity"
      - name: campaign_id
        description: "Unique identifier for each campaign"
      - name: campaign_name
        description: "Descriptive name of the campaign"
      - name: impressions
        description: "Total number of impressions per day per campaign"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
      - name: clicks
        description: "Total number of clicks per day per campaign"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
      - name: are_impressions_gt_clicks
        description: "Boolean flag — true if impressions are greater than clicks"
        tests:
          - not_null
